FROM node:18

WORKDIR /admin

ENV TZ="UTC"

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN npm i -g typescript
RUN yarn build
RUN npx prisma generate

ENV ADMIN_JS_SKIP_BUNDLE="true"

EXPOSE 3000

CMD yarn start
