name: Maven Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - name: Install Docker Compose
        run: |
         sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          
      # ✅ Debug step
      - name: List files in docker
        run: ls -R docker

      # Start Docker Compose
      - name: Start Docker Compose
        run: |
          docker-compose -f docker/docker-compose.yaml up -d
          docker ps

      # Wait for services to be ready
      - name: Wait for services
        run: sleep 15
      - name: Wait for app to be ready
        run: |
          for i in {1..60}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
            if [ "$code" -eq 200 ]; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app... (status code: $code)"
            sleep 5
          done
      # Run Maven tests
      - name: Run Selenium tests
        run: mvn -B clean test -Dbase.url=http://app:3000


      # Stop Docker after tests
      - name: Stop Docker Compose
        if: always()
        run: docker-compose -f docker/docker-compose.yaml down
